config/routes.rb
App::Application.routes.draw do

  get "tunes/destroy_all"
  
  resources :tunes

  resources :notes

  

  devise_for :users

  root :to => "tunes#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  belongs_to :tune

  attr_accessible :file, :version_name
  
  #determine where files are uploaded, needs to be set to user-specific folder
  #the easiest solution is probably just to do :url => :some_method and in that method return a string that you want
  # has_attached_file :file , :path => ":rails_root/public/:id/tunes/:filename"

  has_attached_file :file,
  # :storage => :s3, 
  # :s3_credentials => "#{Rails.root}/config/s3.yml",
  #:path => "/tunes/#{tune.user.id}/:id_:filename"
  :path => :custom_path
  #:path => "/tunes/:id_:filename"

  def custom_path
    "/tunes/:id_:filename"
  end


end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :notes
end

app/models/tune.rb
class Tune < ActiveRecord::Base

	belongs_to :user

	has_many :attachments, :dependent => :destroy

    attr_accessible :name, :attachments_attributes

    accepts_nested_attributes_for :attachments

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tunes

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, :notice => 'Note was successfully created.' }
        format.json { render :json => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, :notice => 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tunes_controller.rb
class TunesController < ApplicationController

  ## can add: , except: [:index, :show]
  before_filter :authenticate_user! 

  # GET /tunes
  # GET /tunes.json
  def index
    #Makes a user only see their tunes
    @tunes = current_user.tunes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tunes }
    end
  end

  # GET /tunes/1
  # GET /tunes/1.json
  def show
    @tune = Tune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tune }
    end
  end

  # GET /tunes/new
  # GET /tunes/new.json
  def new
    @tune = Tune.new
    @tune.attachments.build
    Rails.logger.debug @tune
    Rails.logger.debug @tune.attachments

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tune }
    end
  end

  # GET /tunes/1/edit
  def edit
    @tune = Tune.find(params[:id])
    #@tune = nil if @tune.user != current_user
    #should redirect somewhere nice
  end

  # POST /tunes
  # POST /tunes.json
  def create
    # @tune = Tune.new(params[:tune])
    @tune = current_user.tunes.create(params[:tune])

    respond_to do |format|
      if @tune.save
        format.html { redirect_to @tune, :notice => 'Tune was successfully created.' }
        format.json { render :json => @tune, :status => :created, :location => @tune }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tune.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tunes/1
  # PUT /tunes/1.json
  def update
    @tune = Tune.find(params[:id])

    respond_to do |format|
      if @tune.update_attributes(params[:tune])
        format.html { redirect_to @tune, :notice => 'Tune was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tune.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tunes/1
  # DELETE /tunes/1.json
  def destroy
    @tune = Tune.find(params[:id])
    @tune.destroy

    respond_to do |format|
      format.html { redirect_to tunes_url }
      format.json { head :no_content }
    end
  end

 # DELETE /tunes/1
  # DELETE /tunes/1.json
  def destroy_all
    
    Tune.destroy_all(:user_id => current_user.id)


    respond_to do |format|
      format.html { redirect_to tunes_url }
      format.json { head :no_content }
    end
  end


  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # def link_to_add_fields(name, f, association)
  #   new_object = f.object.send(association).klass.new
  #   id = new_object.object_id
  #   fields = f.fields_for(association, new_object, child_index: id) do |a|
  #     render(association.to_s.singularize + "_fields", f: a)
  #   end
  #   link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  # end
  def link_to_add_fields(f, association)
  	new_object = f.object.send(association).klass.new
  	id = new_object.object_id
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/views/home/index.html.erb
<!-- not being used because root route is being set to tunes/index -->

<!--[if lt IE 7]>
<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->
<!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Some Tunes I Am Learning</a>
      <div class="nav-collapse collapse">
        <form class="navbar-form pull-right">
          <input class="span2" type="text" placeholder="Email">
          <input class="span2" type="password" placeholder="Password">
          <button type="submit" class="btn">Sign in</button>
        </form>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span12">
      
      
    </div>
  </div>
  <hr>
  <footer>
    <p>&copy; Company 2012</p>
  </footer>
</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Some Tunes</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link href='http://fonts.googleapis.com/css?family=Arbutus' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Germania+One' rel='stylesheet' type='text/css'>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tag %>
    </head>

<body>

<!--[if lt IE 7]>
<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->
<!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="">
        <div class="auxiliary">
              <% if user_signed_in? %>
                <a href="/" class="icon-home" ></a>&nbsp;&nbsp;&nbsp;
                <%= link_to '', new_tune_path, :class => "icon-music" %>&nbsp;&nbsp;&nbsp;
                <a href="#myModal" id="userMenu" class="icon-user" data-toggle="modal"></a>
              <% else %>
                <a href="#myModal" id="userMenu" class="icon-user" data-toggle="modal"></a>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="myModalLabel">Account</h3>
  </div>
  <div class="modal-body">
    <% if user_signed_in? %>
      <%= link_to 'Edit Account', edit_user_registration_path, :class => "edit-account"%> <br />
      <%= link_to 'Sign Out', destroy_user_session_path,  :class => "sign-out", :method => :delete %>
      <%= link_to 'Delete All', tunes_destroy_all_path, :data => { :confirm => 'Are you sure?' }, :class => 'icon-remove' %>
      <!-- <strong><%= current_user.email %></strong> -->

    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> <br />
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
      <div class="span12 mainLogo">
          Somes Tunes
      </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span4 offset4">
          <% if notice || alert %>
              <div class="alert">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 <p> <%= notice %> </p>
                 <p> <%= alert %> </p> 
              </div>
            <% end %> 
        </div>
    </div>
  <div class="row-fluid">
    <div class="span8 offset2">
      <%= yield %>
    </div>
  </div>
<!--   <hr>
  <footer>
    <p>&copy; Company 2012</p>
  </footer> -->
</div> <!-- /container -->

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.notes %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Notes:</b>
  <%= @note.notes %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/tunes/_attachment_fields.html.erb
<div class="field">
	<%= f.label :version_Name %>
	<%= f.text_field :version_name %><br />
	<%= f.file_field :file %>
	<%= f.link_to_remove "", :class => 'icon-remove' %>
</div>
<hr />

app/views/tunes/_form.html.erb
<div class="new-form well">
  <%= nested_form_for @tune do |f| %>
    <% if @tune.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tune.errors.count, "error") %> prohibited this tune from being saved:</h2>

        <ul>
        <% @tune.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :tune_Title %>
      <%= f.text_field :name %>
    </div>
    <hr />
    <%= f.fields_for :attachments %>
    
    <%= f.link_to_add "", :attachments, :class => 'icon-plus-sign' %>
     
    <br />
    <br />
    <div class="actions">
      <%= f.submit "Add Tune", :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/tunes/edit.html.erb
<h1>Editing tune</h1>

<%= render 'form' %>

<%= link_to 'Show', @tune %> |
<%= link_to 'Back', tunes_path %>

app/views/tunes/index.html.erb
<div class="accordion">
  <% @tunes.each do |tune| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<%= tune.id %>">
        <%= tune.name %> <br />
      </a>
    </div>
    <div id="collapse<%= tune.id %>" class="accordion-body collapse">
      <div class="accordion-inner">
          <% tune.attachments.each do |attachment| %>
            <div class="tune-version">
              <h4><%= attachment.version_name %></h4>
              <audio controls="control" preload="none" width="100%" src="<%= attachment.file.url %>" type="audio/mp3" >
              </audio>
            </div>
          <% end %>
        <%= link_to '', edit_tune_path(tune), :class => 'icon-edit' %> &nbsp; &nbsp; 
        <%= link_to '', tune, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'icon-remove' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/tunes/new.html.erb
<div class="span6 offset3 new-form">
	<h2>New Tune</h2>
	<%= render 'form' %>
</div>

app/views/tunes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tune.name %>
</p>

<%= link_to 'Edit', edit_tune_path(@tune) %> |
<%= link_to 'Back', tunes_path %>